services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: washmonitor-api
    ports:
      - "8001:8001"
    environment:
      - API_ENV=production
    restart: unless-stopped

  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: washmonitor-agent
    environment:
      - API_URL=http://api:8001
      - WASHER_CAMERA_URL=http://your_camera_url
      - DISCORD_URL=https://your_discord_webhook_url
    depends_on:
      - api
    restart: unless-stopped
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: washmonitor-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped