openapi: 3.0.0
info:
  title: washmonitor-api
  description: This is the API backend for the WashMonitor application
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/v1
paths:
  /sendMessage:
    post:
      summary: Sends a message to a specific device
      description: Sends a message to a specific device based on the device ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  description: The message to send
                  example: "Hello, world!"
                deviceId:
                  type: string
                  description: The ID of the device to send the message to
                  example: "123456"
      responses:
        '200':
          description: Successful creation
        '400':
          description: Invalid input or device id not found
        '500':
          description: Internal server error

