# --- Build Stage ---
FROM node:alpine AS builder

WORKDIR /app

ARG NODE_ENV=production

COPY . .
RUN npm i

EXPOSE 3000

RUN npm run build

CMD ["npm", "start"]

## --- Nginx Stage ---
#FROM nginx:alpine
#
## Copy exported static site from build stage
#COPY --from=builder /app/out /usr/share/nginx/html
#
## Copy custom nginx config
#COPY nginx.conf /etc/nginx/nginx.conf
#
#EXPOSE 8002
#
#CMD ["nginx", "-g", "daemon off;"]