openapi: 3.1.1
info:
  title: washmonitor-agent-api
  description: This is the API served by the washmonitor agent
  version: 1.0.0
servers:
  - url: http://localhost:8001
paths:
  /setAgentStatus:
    post:
      summary: Set the status of the agent to either 'monitor' or 'idle'
      description: This endpoint allows the user to set the status of the agent to either 'monitor' or 'idle'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required: [ status, user ]
                  properties:
                    status:
                      type: string
                      enum: [ monitor ]
                      description: The status must be 'monitor'
                    user:
                      type: string
                      description: The user currently using the washer
                - type: object
                  required: [ status ]
                  properties:
                    status:
                      type: string
                      enum: [ idle ]
                      description: The status must be 'idle'
                    user:
                      type: string
                      description: The user (optional if status is 'idle')
      responses:
        '200':
          description: The status of the agent has been set
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Agent status set successfully
                  status:
                    type: string
                    example: monitor
        '400':
          description: The request was malformed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Malformed request
        '500':
          description: An error occurred while setting the agent status
  /getAgentStatus:
    get:
      summary: Get the status of the agent
      description: This endpoint allows the user to get the status of the agent
      responses:
        '200':
          description: The status of the agent has been retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: idle
                  user:
                    type: string
                    example: Mason
        '500':
          description: An error occurred while getting the agent status